services:
  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: Roomies
    volumes:
      - ./storage/sql/:/docker-entrypoint-initdb.d/
